### ISSUE TITLE
why the embinit.save's length is  one bigger than the length of the wordlist?

### ISSUE THREAD

**Issue by wangjialin114** [thunlp/NSC#1]
hi, i am glad the codes are open-source. 
And i found that the problem as the title said? Is the reason that there is one meaning "UNK" like the id "-1" in the wordlist? If does, which one means the "UNK", the first or the last embeddings in the embinit.save?

**Comment by lan2720** [comment]
Hi, I feel strange about it too.

Another thing puzzles me is where the `wordlist.txt` comes from. Since I try to generate IMDB wordlist using its train.txt and dev.txt. Just get 90000+ words, rather than 100000+ words as authors described.
Is there anything I missed?

**Comment by wangjialin114** [comment]
@lan2720  About the wordlist, i think you should just use the author gives to you. 
About where it comes from , i guess , maybe the original dataset(that have not been split).Then use tokenization to get it.

**Comment by lan2720** [comment]
@wangjialin114 Thanks but I don't think so. Because the authors say they use the datasets provided by Tang. In Tang's zip file, train/dev/test data have been split already. And he didn't provide other files like wordlist.txt. So wordlist.txt was created by the authors using train and dev sets. But now I just cannot get the same result according to this idea.

**Comment by huimchen** [comment]
- @wangjialin114
  Thanks for your question. As you said, there is one "UNK" word embedding in the embinit.save, which is the last embedding.

**Comment by huimchen** [comment]
- @lan2720 
  Thanks for your question. I get the wordlist.txt from a  more original dataset in Tang 2015"Document Modeling with Gated Recurrent Neural Network for Sentiment Classification". And the dataset in this paper is a subset from the original dataset. Maybe I state not so clearly.

**Comment by lan2720** [comment]
@huimchen Thanks for your clear answer!
