### ISSUE TITLE
Will it work without GPU?

### ISSUE THREAD

**Issue by SmillyDog** [thunlp/NSC#10]
hey, recently I was trying to run this code on my computer. Sadly, I don't have any GPU. So I was wondering if this is still gonna work. If not, what changes should I do?

**Comment by huimchen** [comment]
Thanks for your question.
If you don't have a  GPU, you can use a CPU instead of it with the command "THEANO_FLAGS="floatX=float32". But it will be very slow.

**Comment by SmillyDog** [comment]
Wow, thanks for your reply. And this is a relief. I tried this command once, but it didn't have any responding for a long time. So I thought maybe I didn't use it right.
