### ISSUE TITLE
在下载data.zip的IMDB数据中，为什么词向量很多都是0

### ISSUE THREAD

**Issue by bruceluo1991** [thunlp/NSC#12]
@huimchen  您好，我现在了您提供了链接的数据：data.zip，在运行代码中IMDB的实验时，发现在IMDB文件夹下的embinit.save中，在编号比较大（比如超过15000）后，好像词向量都是零向量，请问为什么要将后面的单词的词向量都设置为0向量呢？

**Comment by huimchen** [comment]
感谢您的提问。
初始化向量embinit.save不是人工设置的，而是在语料库里学出来的，具体在论文中也有提及。
