### ISSUE TITLE
使用GPU报内存错误，请问你的theano版本？

### ISSUE THREAD

**Issue by Jockey1993** [thunlp/NSC#14]
你好，我使用THEANO_FLAGS="floatX=float32,device=gpu" python train.py IMDB 10运行一会就会报内存错误，具体错误如下：Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xb09aa0000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
Error when tring to find the memory information on the GPU: an illegal memory access was encountered
Error freeing device pointer 0xb59a00000 (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
device_free: cudaFree() returned an error, but there is already an Python error set. This happen during the clean up when there is a first error and the CUDA driver is in a so bad state that it don't work anymore. We keep the previous error set to help debugging it.CudaNdarray_uninit: error freeing self->devdata. (self=0x7f113c04aef0, self->devata=0xb59a00000)
Error when trying to find the memory information on the GPU: an illegal memory access was encountered
Error allocating 84299200 bytes of device memory (an illegal memory access was encountered). Driver report 0 bytes free and 0 bytes total 
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    model.train(100)
  File "/home/wangj/Work/NSC-master/NSC/src/LSTMModel.py", line 74, in train
    out = self.train_model(self.trainset.docs[i], self.trainset.label[i], self.trainset.length[i],self.trainset.sentencenum[i],self.trainset.wordmask[i],self.trainset.sentencemask[i],self.trainset.maxsentencenum[i])
  File "/home/liutl/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 588, in __call__
    self.fn.thunks[self.fn.position_of_error])
  File "/home/liutl/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 579, in __call__
    outputs = self.fn()
MemoryError: Error allocating 84299200 bytes of device memory (an illegal memory access was encountered).
Apply node that caused the error: GpuElemwise{Composite{[mul(i0, sqr(i1))]},no_inplace}(CudaNdarrayConstant{[[ -1.76432998e-28]]}, GpuAdvancedIncSubtensor1_dev20{inplace,inc}.0)
Inputs shapes: [(1, 1), (105374, 200)]
Inputs strides: [(0, 0), (200, 1)]
Inputs types: [CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, matrix)]
Use the Theano flag 'exception_verbosity=high' for a debugprint of this apply node.
我查了一下有可能和我的theano版本有关系，我的服务器里安装的是0.6的版本，请问你进行实验的时候用的是什么版本？谢谢！ @huimchen

**Comment by huimchen** [comment]
您好，感谢您的提问。
0.7和0.8的版本都用过。
