### ISSUE TITLE
About the result.

### ISSUE THREAD

**Issue by banbhrani** [thunlp/NSC#15]
I have run the code as settings accordingly, but didn't meet the results provided in the Paper.
Could you describe if I made any mistake.
![results](https://user-images.githubusercontent.com/29403868/27250049-22a77726-5357-11e7-9c81-2ef0b5751833.png)

**Comment by huimchen** [comment]
Thanks for your question.
I think this may relate to the process of optimization and parameter initialization which you can adjust.
I can provide the model of the result I tested to you, If you want.

**Comment by banbhrani** [comment]
Thanks for your response. Sure I would love see that model.

**Comment by huimchen** [comment]
OK! Could you give me your email address?

**Comment by banbhrani** [comment]
santosh.banbhrani@gmail.com

**Comment by banbhrani** [comment]
Thanks for your kind cooperation.
