### ISSUE TITLE
训练train的疑问

### ISSUE THREAD

**Issue by yinminggang** [thunlp/NSC#17]
您好，
在训练过程中，为什么要随机选窗口来训练呢？
在LSTMModel.py的方法def train(iters)，lst应该就是随机出iters个窗口的编号，然后去训练这些窗口内的数据，疑问的是，为什么不是每个窗口进行训练，随机选不会影响训练效果吗？
我看到测试test是有对每个窗口数据进行测试。求解？？？？

**Comment by huimchen** [comment]
您好，感谢您的提问。
这里采取的是对训练集随机采样的操作，以防止训练数据的某些特定分布所带来的影响，且当随机采样达到一定轮数，相当于遍历整个训练集。

**Comment by yinminggang** [comment]
好的，明白了，谢谢。
