### ISSUE TITLE
can this be used on Windows computer?

### ISSUE THREAD

**Issue by Sandy4321** [thunlp/NSC#21]
can this be used on Windows computer?

**Comment by huimchen** [comment]
Thanks for your question.
It can be used on Windows if you have installed python, theano and other needed environments already.

**Comment by Sandy4321** [comment]
great thanks
where is a list of needed packages to install, pls?

**Comment by AhmMahya** [comment]
what is the python version ,pls?

**Comment by Sandy4321** [comment]
python 3.6

**Comment by chaiguanpeng** [comment]
python 3.6 has some Syntax error

**Comment by huimchen** [comment]
This program was based on python2 ^ _ ^

**Comment by Sandy4321** [comment]
Can it be updated to Python 3?
Python 2 is obsolete
