### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by cheng-Ye** [thunlp/NSC#22]
i use theano CPU ,it appears the following problems 

  File "d:\Users\compiler1\Anaconda2\lib\site-packages\theano\gof\graph.py", line 381, in __init__
    self.tag = utils.scratchpad()

NameError: global name 'utils' is not defined

how can i fix ut?

**Comment by huimchen** [comment]
Since Theano has stopped updating, this issue will be closed and  implementations  based on other deep learning frameworks are welcome!
