### ISSUE TITLE
您好，想问下这个用户和产品注意力的词典或者矩阵是怎么建立的呢？不太明白。谢谢您的指导！

### ISSUE THREAD

**Issue by 01abc** [thunlp/NSC#23]

**Comment by beyondguo** [comment]
我也是想问这个人问题，整篇论文，这个是最关键的点，却一直避而不谈，只在文章最后面说了一两句不知所云的话。

**Comment by huimchen** [comment]
您好，感谢您的提问。
在这篇工作中，我们为每一个用户或者产品赋予一个向量表示，初始化为零向量。模型通过对每个用户和产品的特定评论的训练，学习每个用户向量和产品向量的表示，进一步利用注意力机制关注到相应的文本单元（句子或者词）。
