### ISSUE TITLE
关于LSTMModel.py的问题

### ISSUE THREAD

**Issue by hungryquiter** [thunlp/NSC#6]
params = []
for layer in layers:
    params += layer.params
    L2_rate = numpy.float32(1e-5)
    for param in params[5:]:
            cost += T.sum(L2_rate * (param * param), acc_dtype='float32')
    gparams = [T.grad(cost, param) for param in params]

打印出的params如下：[E, U, P, Wi1, Wi2, bi, Wo1, Wo2, bo, Wf1, Wf2, bf, Wc1, Wc2, bc, W, v, Wu, Wp, b, Wi1, Wi2, bi, Wo1, Wo2, bo, Wf1, Wf2, bf, Wc1, Wc2, bc, W, v, Wu, Wp, b, W, b, W, b]
想问下，这个为什么从第五个开始，第五个应该是bi。
我的理解这个cost应该是正则化项，为何要从第五个开始，
另外，我想问一下，这里面的E,U,P的值是不是也在随着训练更新。谢谢了。

**Comment by huimchen** [comment]
感谢你的提问！
这里应该是当时的整理错误，应该是3；
EUP也是同时更新的～

**Comment by hungryquiter** [comment]
谢谢

**Comment by yinminggang** [comment]
但是现在下载的github上是param[1:]，这是正确的吗？还是说param内容有变化？感谢。
