### ISSUE TITLE
代码容易跑崩

### ISSUE THREAD

**Issue by jinhlov** [thunlp/NSC#7]
您好！我下载了代码，直接在内存12G的titan的GPU跑train.py，但是迭代到700次时，代码就内存不足崩溃了。
有试过调节batch_size等，但是同样存在这个问题，只是可能能跑久一些。
因为我不太熟悉theano，请问为什么内存这么不稳定，为什么需要内存越来越多？我的GPU配置差于你的吗，才会出现这种跑不下去的情况？

另外，求模型结果，我用tensorflow复现，参数完全一致，在IMDB上只能达到49%，而且此时训练集上过拟合严重。

**Comment by huimchen** [comment]
您好！很感谢您的提问。一般实验迭代到600次之前，就可以达到最好效果了，目前还没有试过更多轮次。我的GPU配置也是12G，我可以尝试更多轮次观察一下。
另外最优模型已经发给你^_^
