### ISSUE TITLE
词向量训练

### ISSUE THREAD

**Issue by jinhlov** [thunlp/NSC#8]
您好，请问代码提供的词向量据论文中说是通过skip-gram训练得到的，请问具体的训练参数是多少，使用了哪个软件包呢？
另外，有尝试过用SSWE做吗？

**Comment by huimchen** [comment]
您好，很感谢您的提问！
我使用的是google发布的c++版本word2vec：https://code.google.com/archive/p/word2vec/
训练参数： -size 200 -window 8 -negative 25 -hs 0 -sample 1e-4 -binary 0 -iter 15
embedding上目前没有尝试过SSWE.
