### ISSUE TITLE
Pre-train the 200-dimensional word embeddings on each dataset

### ISSUE THREAD

**Issue by 691505789** [thunlp/NSC#9]
In you paper, for each dataset,  you pre-train the 200-dimensional word embeddings on each dataset,  I want to ask that what datasets to train the word vector, just the model training dataset like IMDB or with other dataset like wiki ?
 Thank you !

**Comment by huimchen** [comment]
Thanks for your question. 
As mentioned in the paper, we pre-train the 200-dimensional word embeddings on each dataset in (Tang et al. ,2015a), such as IMDB and Yelp.
